name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: actions-checkout
        uses: actions/checkout@v3
      - name: install modules
        run: yarn install
      - name: project build
        run: yarn run build
      - name: eslint fix
        run: yarn lint:fix
      - name: prettier
        run: yarn run format
